spring:
  cloud:
    stream:
      bindings:
          messageFromDeviceConfiguration: 
            destination: input
            binder: rabbit1
            group: integration 
            bindings:
          messageToDeviceConfiguration: 
            destination: output
            binder: rabbit2
            group: integration
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbit:
                addresses: ef102pocmom0v.epi.securitasdirect.local:5672
                username: integration
                password: integration
                virtual-host: vhintegration
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbit:
                addresses: ef102pocmom0v.epi.securitasdirect.local:5672
                username: integration
                password: integration
                virtual-host: vhintegration              
                    

feign:
  client:
    config:
      osbFeignClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        #errorDecoder: com.example.SimpleErrorDecoder
        #retryer: com.example.SimpleRetryer
        #requestInterceptors:
        #  - com.example.FooRequestInterceptor
        #  - com.example.BarRequestInterceptor
        #decode404: false
        #encoder: com.example.SimpleEncoder
        #decoder: com.example.SimpleDecoder
        #contract: com.example.SimpleContract


# TODO: REVIEW IF YOUR APPLICATION NEEDS TRACE THIS PARAMETER OR MORE (this is an example with installationNumber)      
# Spring Cloud Sleuth tracing extra fields to propagate (HTTP/Rest and messaging)
  sleuth:
    propagation-keys:
    - installationNumber
    
# MDCFilter: Keys for get tracing extra fields from HTTP headers
http:
  headers:
    installationNumber: installationNumber
# MDCFilter: Keys for set tracing extra fields to the MDC context
logging:
  mdc:
    installationNumber: installationNumber